[package]
name = "pwo"
version = "0.1.0"
edition = "2024"

[dependencies]
bigdecimal = "0.4.10"
chrono = "0.4.43"
chumsky = "0.12.0"
colored = "3.1.1"
control = "1.0.0"
pest_derive = "2.8.5"
rust_decimal_macros = "1.40.0"
thiserror = "2.0.17"
